GET http://localhost:3004/settings

###

POST http://localhost:3004/settings/new
Content-Type: application/json

{
    "text": "Comedies"
}

###

DELETE http://localhost:3004/settings/delete/62bd1ee90d86a778c1feafc3

### 

GET http://localhost:3004/register